package dam_a51597.virtual_library

fun main() {
    val library = Library("Central Library")

    val digitalBook = DigitalBook(
        "Kotlin in Action",
        "Dmitry Jemerov",
        // Explanation as to why this value was turned into a string can be found in line 6-9 of the Book Class
        "2017",
        5,
        4.5,
        // From string to Enum type as it is more professional and only provides me more knowledge about the programming language
        FormatType.PDF
    )

    val physicalBook = PhysicalBook(
        "Clean Code",
        "Robert C. Martin",
        "2008",
        3,
        650,
        true
    )

    val classicBook = PhysicalBook(
        "1984",
        "George Orwell",
        "1949",
        2,
        400,
        false
    )

    library.addBook(digitalBook)
    library.addBook(physicalBook)
    library.addBook(classicBook)

    library.showBooks()

    println("\n--- Borrowing Books ---")
    library.borrowBook("Clean Code")
    library.borrowBook("1984")
    library.borrowBook("1984")
    library.borrowBook("1984") // Should fail - no copies left

    println("\n--- Returning Books ---")
    library.returnBook("1984")

    println("\n--- Search by Author ---")
    library.searchByAuthor("George Orwell")

    // ======= More examples to test additional functionalities added in 6.2 ========

    // These examples were AI generated by Claude Opus 4.6 to accelerate the construction of a demonstration (That
    // wasn't even requested in the assignment, but add for completion’ sake). This was the only use of AI used in the
    // package.

    println("\n--- Total Books Added (Companion Object) ---")
    println("Total books added to library: ${Library.getTotalBooksCreated()}")

    println("\n--- Storage Info ---")
    println(digitalBook.getStorageInfo())
    println(physicalBook.getStorageInfo())

    println("\n--- Era Classification ---")
    println("'${digitalBook.title}' era: ${digitalBook.publicationYear}")   // 2017 -> Contemporary
    println("'${physicalBook.title}' era: ${physicalBook.publicationYear}") // 2008 -> Modern
    println("'${classicBook.title}' era: ${classicBook.publicationYear}")   // 1949 -> Classic

    println("\n--- Library Member ---")
    val member = LibraryMember("Alice")
    println(member)

    println("\n--- Member Borrows Books ---")
    member.borrowBook(library, "Kotlin in Action")
    member.borrowBook(library, "Clean Code")
    member.showBorrowedBooks()

    println("\n--- Member Returns a Book ---")
    member.returnBook(library, "Kotlin in Action")
    member.showBorrowedBooks()

    println("\n--- Member Borrows Non-Existent Book ---")
    member.borrowBook(library, "Unknown Book")

    println("\n--- Member Returns a Book Not Borrowed ---")
    member.returnBook(library, "1984")

    println("\n--- Borrow/Return Non-Existent Book via Library ---")
    library.borrowBook("Non-Existent Book")
    library.returnBook("Non-Existent Book")

    println("\n--- Member Info ---")
    println(member)
}